version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      docusaurus:
        applies-to: version-updates
        patterns:
          - "@docusaurus/*"
          - "docusaurus-*"
      rijkshuisstijl:
        applies-to: version-updates
        patterns:
          - "@rijkshuisstijl-community/*"
