import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // gettingStartedSidebar: [{type: 'autogenerated', dirName: '.'}],
  overview: [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "doc",
          id: "api-ontwikkeling/index",
          label: "API Ontwikkeling",
        },
        {
          type: "doc",
          id: "front-end/index",
          label: "Front-end",
        },
        {
          type: "doc",
          id: "data/index",
          label: "Data & Interoperabiliteit",
        },
        {
          type: "doc",
          id: "open-source/index",
          label: "Open Source",
        },
        {
          type: "doc",
          id: "devops/index",
          label: "DevOps & Platform",
        },
        {
          type: "doc",
          id: "security/index",
          label: "Security",
        },
        {
          type: "doc",
          id: "leidraad/index",
          label: "NeRDS leidraad softwareontwikkeling",
        },
      ],
    },
  ],
  "api-ontwikkeling": [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "category",
          label: "API Ontwikkeling",
          link: { type: "doc", id: "api-ontwikkeling/index" },
          items: [
            {
              type: "autogenerated",
              dirName: "api-ontwikkeling",
            },
          ],
        },
      ],
    },
  ],
  data: [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "category",
          label: "Data & Interoperabiliteit",
          link: { type: "doc", id: "data/index" },
          items: [
            {
              type: "autogenerated",
              dirName: "data",
            },
          ],
        },
      ],
    },
  ],
  "front-end": [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "category",
          label: "Front-end",
          link: { type: "doc", id: "front-end/index" },
          items: [
            {
              type: "autogenerated",
              dirName: "front-end",
            },
          ],
        },
      ],
    },
  ],
  devops: [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "category",
          label: "DevOps & Platform",
          link: { type: "doc", id: "devops/index" },
          items: [
            {
              type: "autogenerated",
              dirName: "devops",
            },
          ],
        },
      ],
    },
  ],
  "open-source": [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "category",
          label: "Open Source",
          link: { type: "doc", id: "open-source/index" },
          items: [
            {
              type: "autogenerated",
              dirName: "open-source",
            },
          ],
        },
      ],
    },
  ],
  security: [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "category",
          label: "Security",
          link: { type: "doc", id: "security/index" },
          items: [
            {
              type: "autogenerated",
              dirName: "security",
            },
          ],
        },
      ],
    },
  ],
  leidraad: [
    {
      type: "category",
      label: "Kennisbank",
      link: { type: "doc", id: "index" },
      items: [
        {
          type: "category",
          label: "NeRDS leidraad softwareontwikkeling",
          link: { type: "doc", id: "leidraad/index" },
          items: [
            {
              type: "autogenerated",
              dirName: "leidraad",
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
