name: Build & Link Check

on:
  pull_request:
  push:
      branches:
        - main
    
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docusaurus site
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: docusaurus-build
          path: build

  check-links:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: docusaurus-build
          path: build

      - name: Run Linkinator to check external links
        uses: JustinBeckwith/linkinator-action@v1
        continue-on-error: true
        with:
          paths: "build"
          recurse: true
          config: "./linkinator.config.json"
          verbosity: "ERROR"
          timeout: 5000
          retry: 3

  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: serve
          tags: |
            ghcr.io/developer-overheid-nl/don-site:latest
            ghcr.io/developer-overheid-nl/don-site:${{ github.sha }}
