name: Build & Link Check

on:
  push:
    branches:
      - external-link-checker

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: docusaurus-build
          path: build

  check-links:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: docusaurus-build
          path: build

      - name: Run Linkinator to check external links
        uses: JustinBeckwith/linkinator-action@v1
        with:
          paths: "build"
          recurse: true
          config: "./linkinator.config.json"
          verbosity: "error"

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-links
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: serve
          tags: |
            ghcr.io/developer-overheid-nl/don-site:latest
            ghcr.io/developer-overheid-nl/don-site:${{ github.sha }}