name: Check links

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docusaurus site
        run: pnpm run build

      - name: Run Linkinator to check links
        uses: JustinBeckwith/linkinator-action@f62ba0c110a76effb2ee6022cc6ce4ab161085e3
        with:
          paths: "build"
          recurse: true
          cleanUrls: true
          config: "./linkinator.config.json"
          verbosity: "ERROR"
          timeout: 5000
          retry: true
          retryErrors: true
          retryErrorsCount: 3
