name: Check WCAG compliance

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name."
        required: true
        default: "main"
# on:
#   schedule:
#     - cron: '0 2 * * 0'

jobs:
  check-wcag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docusaurus site
        run: pnpm run build

      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          content-types: |
            {
              "css": "text/css",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "svg": "image/svg+xml",
              "txt": "text/plain",
              "xml": "text/xml"
            }
          port: 3000
          directory: build/
          index-files: |
            ["index.html"]

      - name: Run Axe to check for WCAG compliance
        run: node scripts/wcag-sitemap-check.js

      - name: Upload report to Slack
        if: always()
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        run: |
          curl -X POST -H "Authorization: Bearer $SLACK_TOKEN" \
            -H 'Content-type: application/json' \
            --data "{\"channel\":\"$CHANNEL_ID\",\"text\":\"WCAG rapport van deze week is zojuist aangemaakt. Zie bijlage voor details.\"}" \
            https://slack.com/api/chat.postMessage

          if [ -f wcag-report.txt ]; then
            curl -F file=@wcag-report.txt \
              -F "channels=$CHANNEL_ID" \
              -F "initial_comment=WCAG issues gevonden (zie bestand voor details)." \
              -H "Authorization: Bearer $SLACK_TOKEN" \
              https://slack.com/api/files.upload
          fi
