name: Check WCAG compliance

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name."
        required: true
        default: "main"

jobs:
  check-wcag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install ts-node and typescript globally
        run: npm install -g ts-node typescript

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Install Chrome driver for Axe
        run: npx browser-driver-manager install chrome

      - name: Build Docusaurus site
        run: pnpm run build
      
      - name: Serve Files
        uses: Eun/http-server-action@v1
        with:
          content-types: |
            {
              "css": "text/css",
              "html": "text/html",
              "ico": "image/x-icon",
              "jpeg": "image/jpeg",
              "jpg": "image/jpeg",
              "js": "text/javascript",
              "json": "application/json",
              "png": "image/png",
              "svg": "image/svg+xml",
              "txt": "text/plain",
              "xml": "text/xml"
            }
          port: 3000
          directory: build/
          index-files: |
            ["index.html"]

      - name: Run Axe to check for WCAG compliance
        run:  NODE_OPTIONS="--loader ts-node/esm" pnpm exec ts-node scripts/wcag-sitemap-check.ts

