name: Check WCAG compliance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 0"

jobs:
  check-wcag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docusaurus site
        run: pnpm run build

      - name: Serve Files
        run: |
          npx --yes serve build/ --listen 3000 &
          npx --yes wait-on http://localhost:3000

      - name: Run Axe to check for WCAG compliance
        run: node scripts/wcag-sitemap-check.js

      - name: Upload WCAG report to Slack
        if: always()
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95
        with:
          method: files.uploadV2
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
            initial_comment: "WCAG rapport:"
            file: "./wcag-report.txt"
            filename: "wcag-report.txt"
